17 analyze the begin of the client http request in a timeout scenario
aLeuleu/webserv pull request #41
Opened 2023-10-25 14:55 UTC by aLeuleu

2023-10-25 20:41 UTC, tdameros requested changes

2023-10-25 20:41 UTC, tdameros commented on src/HttpMessages/HttpRequest.cpp
> +	if (httpVersion != "HTTP/1.1"){
Add define for HTTP Version

2023-10-25 20:42 UTC, aLeuleu commented
I need to merge main
and
i need to put a macro for HTTP_VERSION (NB this macro already exist in http response

2023-10-26 15:39 UTC, tdameros approved these changes

2023-10-26 16:31 UTC, merged