Max client body size
aLeuleu/webserv pull request #55
Opened 2023-10-30 22:41 UTC by aLeuleu

2023-10-30 22:50 UTC, aLeuleu commented
![image](https://github.com/aLeuleu/webserv/assets/97832618/181ec60a-f61e-4748-a374-32efaecc5abf)

WOOOOOOOOW so beautiful

2023-10-31 07:01 UTC, tdameros requested changes

2023-10-31 07:01 UTC, tdameros commented on src/HttpMessages/HttpRequest.cpp
>  		coloredLog("Lexer error : ", getErrors(), RED);
Replace it by logging

2023-10-31 07:01 UTC, tdameros commented on src/HttpMessages/HttpResponse.cpp
>  	coloredLog("Building...", "\"" + _request.getMethod() + "\"", BLUE);
Replace it by logging

2023-10-31 07:01 UTC, tdameros commented on src/HttpMessages/HttpResponse.cpp
>  		coloredLog("No index valid: ", _requestUri, RED);
Replace it by logging

2023-10-31 07:01 UTC, tdameros commented on src/HttpMessages/HttpResponse.cpp
> +	coloredLog("No index found: ", _location->getURI(), RED);
Same

2023-10-31 07:01 UTC, tdameros commented on src/HttpMessages/HttpResponse.cpp
>  	coloredLog("pathToFile: ", pathToFile, YELLOW);
Replace it by logging

2023-10-31 07:01 UTC, tdameros commented on src/HttpMessages/HttpResponse.cpp
>  	coloredLog("File not found: ", pathToFile, RED);
Same

2023-10-31 07:01 UTC, tdameros commented on src/server/Server.cpp
>  	}
Replace coloredLog by logging

2023-10-31 14:40 UTC, tdameros approved these changes

2023-10-31 14:41 UTC, merged